#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("heariit_ma.Resource", IsApplication=true)]

namespace heariit_ma
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int actionBarBackgroundColor = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int actionBarTextColor = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int auriculares = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int CategoryText = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int artist = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int category_name = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int imageView1 = 2131165188;
			
			// aapt resource value: 0x7f070016
			public const int imageView_Album = 2131165206;
			
			// aapt resource value: 0x7f070013
			public const int linearLayout = 2131165203;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout2 = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int listCategory = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int listView1 = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int loginButtonSignIn = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int loginButtonSignUp = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int loginEmailText = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int loginLinearLayout = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int loginPasswordText = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int relativeLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int relativeLayout5 = 2131165185;
			
			// aapt resource value: 0x7f070015
			public const int reproductive_artist = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int reproductive_title = 2131165204;
			
			// aapt resource value: 0x7f07001f
			public const int signupBackBtn = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int signupClearBtn = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int signupEmailText = 2131165210;
			
			// aapt resource value: 0x7f070017
			public const int signupFirstNameText = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int signupLastNameText = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int signupPasswordText1 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int signupPasswordText2 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int signupSignUpBtn = 2131165213;
			
			// aapt resource value: 0x7f070019
			public const int signupUsernameText = 2131165209;
			
			// aapt resource value: 0x7f07000b
			public const int textView1 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int textView2 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int textView3 = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int title = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CategoryLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemCategory = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ItemRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Reproductive = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SignUpLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int bad_connection = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int bad_email = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int empty_field = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int error_not_available = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int error_password_not_equal = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int failed_credentials = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int signup_message = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int unexpected_error = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int warning_not_songs = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int welcome_message = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyAppTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_ActionBarStyle = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
